AWSTemplaterFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Implements save for later for mobile
Parameters:
  Stack:
    Description: Stack name
    Type: String
    Default: mobile-notifications
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - CODE
      - PROD
  App:
    Description: Application name
    Type: String
    Default: save-for-later
  DeployBucket:
    Description: S3 Bucket where riff-raff uploads artifacts on deploy
    Type: String
    Default: mobile-apps-api-dist
  HostedZoneId:
    Description: Id of HostedZone
    Type: String
  HostedZoneName:
    Description: Name of HostedZone
    Type: String
  CertArn:
    Description: ACM Certificate ARN
    Type: String

Resources:
  SaveForLaterApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "1.0.0"
          title: !Ref App
        paths:
          "/syncedPrefs/me/savedArticles":
            post:
              x-amazon-api-gateway-information:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${/syncedPrefs/me/savedArticles.Arn}/invocations
              consumes:
              - application/json
              produces:
              - application/json
              response:
                "200"
                  "descriptiom": "200 response"


  ApiDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertArn
      DomainName: !Sub ${App}-${HostedZoneName}

  ApiRoute53:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref ApiDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Whatthfckgoeshere
            DNSName: !GetAtt
              - ApiDomainName
              - DistributionDomainName

  ApiMappingL
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomainName
      RestApiId: !Ref SaveForLaterApi
      Stage: !Ref Stage

  updateSyncedPrefs:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.gu.sfl.lambda.SaveForLater::post
      Runtime: java8
      CodeUri:
        Bucket: !Ref DeployBucket
        Key: !Sub ${Stack}/${Stage}/${App}/${App}.jar





